name: Build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build . -t gopalgtm001/node-todo:latest
      - name: Build Docker image
        run: docker push gopalgtm001/node-todo:latest
      - name: run Docker image
        run: docker run -d -p 8000:8000 node-todo
            
