name: Build,Analyze,scan
on:
  push:
    branches:
      - main
jobs:
  deploy:
   needs: build-analyze-scan
   runs-on: [self-hosted]
   steps:
      - name: docker show conatiners
        run: docker ps
