name: Build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Copy Docker Compose files to EC2 instance
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build . -t gopalgtm001/node-todo:latest
      - name: Build Docker image
        run: docker push gopalgtm001/node-todo:latest
      - name: run Docker image
        run: docker run -d -p 8000:8000 node-todo
            
